# Generated by Django 5.1 on 2024-10-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_brand_owner_category_owner_model_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="category.category"
            ),
        ),
    ]
