# Generated by Django 5.1.2 on 2024-12-18 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_created_at_alter_cartitem_cart'),
        ('product', '0010_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.color'),
            preserve_default=False,
        ),
    ]
