# Generated by Django 5.1 on 2024-10-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("role_request", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
