# Generated by Django 5.1 on 2024-10-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("role_request", "0002_alter_rolerequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolerequest",
            name="denied_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
