# Generated by Django 5.1 on 2024-10-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("role_request", "0003_rolerequest_denied_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolerequest",
            name="canceled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
