# Generated by Django 5.1 on 2024-10-27 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("role_request", "0004_rolerequest_canceled_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rolerequest",
            name="canceled_time",
        ),
    ]
