# Generated by Django 5.1 on 2024-10-29 16:47

import django.db.models.deletion
import order.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_code",
                    models.CharField(
                        default=order.models.generate_order_code,
                        max_length=7,
                        unique=True,
                    ),
                ),
                (
                    "shipment_price",
                    models.DecimalField(
                        decimal_places=2, default=10.0, editable=False, max_digits=10
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("address", models.TextField()),
                ("payment_type", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("canceled", "Canceled"),
                            ("successful", "Successful"),
                            ("pending", "Pending to Pay"),
                            ("delivered", "Delivered"),
                            ("returned", "Returned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
