# Generated by Django 5.1.2 on 2024-12-13 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.shipmentprice'),
        ),
    ]
