# Generated by Django 5.1.2 on 2024-12-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_shipmentprice_alter_order_shipment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit card')], default='cash', max_length=20),
        ),
    ]
