# Generated by Django 5.1.2 on 2024-12-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at_date',
            field=models.DateField(default='1403-09-27'),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
