# Generated by Django 5.1.2 on 2024-12-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_created_at_order_created_at_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at_date',
            field=models.DateField(default='1403-09-28'),
        ),
    ]
