# Generated by Django 5.1.2 on 2024-12-18 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_created_at_date'),
        ('product', '0010_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.color'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at_date',
            field=models.DateField(default='1403-09-29'),
        ),
    ]
