# Generated by Django 5.1.2 on 2024-12-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderitem_color_alter_order_created_at_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at_date',
            field=models.DateField(default='1403-10-05'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'نقد'), ('credit_card', 'درگاه پرداخت')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'کنسل'), ('successful', 'موفق'), ('pending', 'در انتظار پرداخت'), ('delivered', 'تحویل شده'), ('returned', 'مرجوع')], default='pending', max_length=20),
        ),
    ]
