# Generated by Django 5.1 on 2024-10-29 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="count",
            new_name="quantity",
        ),
    ]
