# Generated by Django 5.1.2 on 2024-11-15 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_subcategory_category_alter_subcategory_name_and_more'),
        ('product', '0002_rename_count_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='category.category'),
            preserve_default=False,
        ),
    ]
