# Generated by Django 5.1.2 on 2024-11-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_color_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo4',
        ),
    ]
