# Generated by Django 5.1.2 on 2024-11-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-11-01T18:29'),
            preserve_default=False,
        ),
    ]
