# Generated by Django 5.1.2 on 2024-10-22 14:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="additional_information",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="apartment",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_birth",
            field=models.DateField(
                blank=True, default=users.models.persian_date, null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="floor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phonenumber",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="register_date",
            field=models.DateField(default=users.models.persian_date),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("seller", "Seller"),
                    ("admin", "Admin"),
                ],
                default="customer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="street",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="zip_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
